# Generated by Django 5.1.6 on 2025-02-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
